# Generated by Django 6.0.5 on 2026-05-26 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('image', models.ImageField(upload_to='banners/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
                ('position', models.CharField(choices=[('hero', 'Hero Slider'), ('promo', 'Promotional Banner'), ('category', 'Category Banner')], db_index=True, default='hero', max_length=20)),
                ('background_color', models.CharField(blank=True, max_length=20)),
                ('text_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['position', 'is_active'], name='banners_positio_9fe3d8_idx')],
            },
        ),
    ]
